// Generated by CoffeeScript 1.3.1
(function() {

  $(document).ready(function() {
    return $('#communities').dataTable({
      "sDom": "<'row'<'span6'l><'span12'f>r>t<'row'<'span6'i><'span6'p>>",
      "bPaginate": false
    });
  });

}).call(this);
